package io.github.sooakim.remote.exception

class UserNotFoundException : RuntimeException()